# Generated by Django 5.2.9 on 2025-12-29 14:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField(unique=True)),
                ('region', models.CharField(choices=[('EU', 'Europe'), ('WORLD', 'World'), ('RU', 'Russia')], max_length=10)),
                ('topic', models.CharField(choices=[('economy', 'Economy'), ('politics', 'Politics'), ('it', 'IT'), ('auto', 'Auto')], max_length=20)),
                ('source_class', models.CharField(choices=[('agency', 'Agency'), ('official', 'Official'), ('stats', 'Stats'), ('industry', 'Industry'), ('commentary', 'Commentary')], max_length=20)),
                ('cadence', models.CharField(choices=[('hot', 'Hot (5–15m)'), ('medium', 'Medium (1–3h)'), ('cold', 'Cold (6–24h)')], default='medium', max_length=10)),
                ('is_enabled', models.BooleanField(default=True)),
                ('last_fetch_at', models.DateTimeField(blank=True, null=True)),
                ('etag', models.CharField(blank=True, max_length=300, null=True)),
                ('last_modified', models.CharField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FetchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('elapsed_ms', models.IntegerField(blank=True, null=True)),
                ('bytes_received', models.IntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fetch_logs', to='intel.source')),
            ],
        ),
        migrations.CreateModel(
            name='RawItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(blank=True, max_length=500)),
                ('url', models.URLField()),
                ('title', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('item_hash', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='intel.source')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source', 'item_hash'), name='uniq_source_itemhash')],
            },
        ),
    ]
