# Generated by Django 5.2.9 on 2025-12-29 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_url', models.URLField(blank=True)),
                ('lang', models.CharField(blank=True, max_length=12)),
                ('title', models.TextField(blank=True)),
                ('text', models.TextField(blank=True)),
                ('extracted_at', models.DateTimeField(blank=True, null=True)),
                ('extract_error', models.TextField(blank=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='article', to='intel.rawitem')),
            ],
        ),
    ]
