# Generated by Django 5.2.9 on 2025-12-29 23:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel', '0002_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('region', models.CharField(blank=True, max_length=16)),
                ('topic', models.CharField(blank=True, max_length=16)),
                ('evidence_level', models.IntegerField(choices=[(0, '0: anonymous/insider'), (1, '1: media reprints'), (2, '2: has primary source'), (3, '3: multi-class confirmation')], default=1)),
                ('cluster_key', models.CharField(db_index=True, max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='intel.event')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event_item', to='intel.rawitem')),
            ],
        ),
    ]
