# Generated by Django 5.2.9 on 2025-12-30 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel', '0003_event_eventitem'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='eventitem',
            index=models.Index(fields=['event', '-created_at'], name='intel_event_event_i_6441a4_idx'),
        ),
    ]
