# Generated by Django 5.2.9 on 2026-06-09 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel', '0004_eventitem_intel_event_event_i_6441a4_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedMedicalNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('meta_description', models.CharField(blank=True, max_length=320)),
                ('body', models.TextField(help_text='Основной текст новости. На первом этапе храним Markdown.')),
                ('source_note', models.TextField(blank=True, help_text='Краткое примечание об источниках и основании материала.')),
                ('disclaimer', models.TextField(default='Материал носит информационный характер и не заменяет консультацию врача. Интерпретацию результатов анализов должен проводить специалист с учётом жалоб, анамнеза и других данных пациента.')),
                ('quality_score', models.IntegerField(default=0, help_text='Внутренняя оценка качества/готовности материала.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('approved', 'Approved'), ('published', 'Published'), ('rejected', 'Rejected'), ('error', 'Error')], db_index=True, default='review', max_length=20)),
                ('llm_model', models.CharField(blank=True, max_length=120)),
                ('llm_prompt', models.TextField(blank=True)),
                ('llm_response_raw', models.TextField(blank=True)),
                ('llm_elapsed_ms', models.IntegerField(blank=True, null=True)),
                ('llm_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalBrief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('angle', models.TextField(blank=True, help_text='Редакционный угол: как именно подать событие для пациентов.')),
                ('target_keyword', models.CharField(blank=True, help_text='Главная SEO-фраза.', max_length=300)),
                ('secondary_keywords', models.TextField(blank=True, help_text='Дополнительные ключевые фразы, по одной на строку.')),
                ('facts', models.TextField(blank=True, help_text='Подтверждённые факты, которые можно использовать в тексте.')),
                ('source_urls', models.TextField(blank=True, help_text='URL источников, по одному на строку.')),
                ('audience', models.CharField(default='пациенты медицинской лаборатории', max_length=200)),
                ('region_text', models.CharField(default='Владикавказ и Северная Осетия', max_length=200)),
                ('safety_notes', models.TextField(blank=True, help_text='Ограничения: что нельзя утверждать, обещать или рекомендовать.')),
                ('disclaimer_required', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('used', 'Used'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-extracted_at']},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='fetchlog',
            options={'ordering': ['-fetched_at']},
        ),
        migrations.AlterModelOptions(
            name='rawitem',
            options={'ordering': ['-published_at', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ['region', 'topic', 'name']},
        ),
        migrations.AlterField(
            model_name='event',
            name='region',
            field=models.CharField(blank=True, db_index=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='event',
            name='topic',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='source',
            name='topic',
            field=models.CharField(choices=[('economy', 'Economy'), ('politics', 'Politics'), ('it', 'IT'), ('auto', 'Auto'), ('medicine', 'Medicine'), ('labs', 'Laboratory diagnostics')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['lang'], name='intel_artic_lang_4476b1_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['extracted_at'], name='intel_artic_extract_3f410a_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['topic', 'region', '-updated_at'], name='intel_event_topic_0180d1_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['evidence_level', '-updated_at'], name='intel_event_evidenc_c1d274_idx'),
        ),
        migrations.AddIndex(
            model_name='fetchlog',
            index=models.Index(fields=['source', '-fetched_at'], name='intel_fetch_source__cda403_idx'),
        ),
        migrations.AddIndex(
            model_name='fetchlog',
            index=models.Index(fields=['status_code', '-fetched_at'], name='intel_fetch_status__89561b_idx'),
        ),
        migrations.AddIndex(
            model_name='rawitem',
            index=models.Index(fields=['source', '-published_at'], name='intel_rawit_source__657ca4_idx'),
        ),
        migrations.AddIndex(
            model_name='rawitem',
            index=models.Index(fields=['created_at'], name='intel_rawit_created_ee1ded_idx'),
        ),
        migrations.AddIndex(
            model_name='source',
            index=models.Index(fields=['region', 'topic', 'is_enabled'], name='intel_sourc_region_9c976c_idx'),
        ),
        migrations.AddIndex(
            model_name='source',
            index=models.Index(fields=['cadence', 'is_enabled'], name='intel_sourc_cadence_1c5c58_idx'),
        ),
        migrations.AddField(
            model_name='medicalbrief',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_briefs', to='intel.event'),
        ),
        migrations.AddField(
            model_name='generatedmedicalnews',
            name='brief',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_news', to='intel.medicalbrief'),
        ),
        migrations.AddIndex(
            model_name='medicalbrief',
            index=models.Index(fields=['status', '-created_at'], name='intel_medic_status_df742e_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalbrief',
            index=models.Index(fields=['event', 'status'], name='intel_medic_event_i_aa22c6_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedmedicalnews',
            index=models.Index(fields=['status', '-created_at'], name='intel_gener_status_590425_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedmedicalnews',
            index=models.Index(fields=['slug'], name='intel_gener_slug_eca800_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedmedicalnews',
            index=models.Index(fields=['published_at'], name='intel_gener_publish_3d9514_idx'),
        ),
    ]
