# Generated by Django 5.2.9 on 2026-07-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel', '0005_generatedmedicalnews_medicalbrief_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedmedicalnews',
            name='image_topic',
            field=models.CharField(blank=True, db_index=True, help_text='Закрытый ключ визуальной темы, выбранный LLM для сопоставления с изображением.', max_length=64),
        ),
    ]
