# Generated by Django 5.2.9 on 2026-07-08 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel', '0006_generated_medical_news_image_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionalDigest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('digest_type', models.CharField(db_index=True, default='regional', max_length=32)),
                ('region_code', models.CharField(blank=True, db_index=True, max_length=32)),
                ('region_label', models.CharField(blank=True, max_length=200)),
                ('region_query', models.TextField(blank=True, help_text='Маркеры региона через запятую, например: рсо-алания, северная осетия, владикавказ')),
                ('topic', models.CharField(blank=True, db_index=True, max_length=32)),
                ('period_start', models.DateTimeField(db_index=True)),
                ('period_end', models.DateTimeField(db_index=True)),
                ('criteria', models.JSONField(blank=True, default=dict)),
                ('evidence_pack', models.JSONField(blank=True, default=dict)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=320)),
                ('meta_description', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
                ('source_map', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('review', 'Review'), ('published', 'Published'), ('rejected', 'Rejected'), ('error', 'Error')], db_index=True, default='draft', max_length=20)),
                ('llm_model', models.CharField(blank=True, max_length=500)),
                ('llm_prompt', models.TextField(blank=True)),
                ('llm_response_raw', models.TextField(blank=True)),
                ('llm_elapsed_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('llm_error', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-period_end', '-id'],
                'indexes': [models.Index(fields=['region_code', 'topic', '-period_end'], name='intel_rd_region_topic_idx'), models.Index(fields=['status', '-created_at'], name='intel_rd_status_created_idx')],
            },
        ),
        migrations.CreateModel(
            name='RegionalDigestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('relevance_score', models.FloatField(default=0)),
                ('selection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('digest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digest_items', to='intel.regionaldigest')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regional_digest_items', to='intel.event')),
            ],
            options={
                'ordering': ['position', 'id'],
                'indexes': [models.Index(fields=['digest', 'position'], name='intel_rditem_position_idx')],
                'constraints': [models.UniqueConstraint(fields=('digest', 'event'), name='uniq_regional_digest_event')],
            },
        ),
    ]
