# Generated by Django 5.2.9 on 2026-07-12 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel', '0007_regional_digest_foundation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomotiveBrief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('angle', models.TextField(blank=True, help_text='Редакционный угол материала для автовладельцев.')),
                ('target_keyword', models.CharField(blank=True, help_text='Главная SEO-фраза.', max_length=300)),
                ('secondary_keywords', models.TextField(blank=True, help_text='Дополнительные SEO-фразы, по одной на строку.')),
                ('facts', models.TextField(blank=True, help_text='Подтверждённые факты, разрешённые для генерации.')),
                ('source_urls', models.TextField(blank=True, help_text='Ссылки на источники, по одной на строку.')),
                ('audience', models.CharField(default='автовладельцы и клиенты автосервиса', max_length=200)),
                ('region_text', models.CharField(default='Владикавказ и Северная Осетия', max_length=200)),
                ('safety_notes', models.TextField(blank=True, help_text='Ограничения и утверждения, которые нельзя использовать.')),
                ('disclaimer_required', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('used', 'Used'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automotive_briefs', to='intel.event')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedAutomotiveNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('meta_description', models.CharField(blank=True, max_length=320)),
                ('body', models.TextField(help_text='Основной текст новости в Markdown.')),
                ('source_note', models.TextField(blank=True, help_text='Краткое примечание об источниках материала.')),
                ('source_urls', models.JSONField(blank=True, default=list, help_text='Нормализованные ссылки на первичные источники.')),
                ('image_topic', models.CharField(blank=True, db_index=True, help_text='Закрытый ключ автомобильной темы изображения.', max_length=64)),
                ('disclaimer', models.TextField(default='Материал носит информационный характер. Точную причину неисправности и необходимость ремонта следует определять после диагностики автомобиля специалистом.')),
                ('quality_score', models.PositiveSmallIntegerField(default=0, help_text='Внутренняя оценка качества материала.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('approved', 'Approved'), ('published', 'Published'), ('rejected', 'Rejected'), ('error', 'Error')], db_index=True, default='review', max_length=20)),
                ('llm_model', models.CharField(blank=True, max_length=120)),
                ('llm_prompt', models.TextField(blank=True)),
                ('llm_response_raw', models.TextField(blank=True)),
                ('llm_elapsed_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('llm_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('brief', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_news', to='intel.automotivebrief')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='automotivebrief',
            index=models.Index(fields=['status', '-created_at'], name='intel_autom_status_f946b2_idx'),
        ),
        migrations.AddIndex(
            model_name='automotivebrief',
            index=models.Index(fields=['event', 'status'], name='intel_autom_event_i_f86439_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedautomotivenews',
            index=models.Index(fields=['status', '-created_at'], name='intel_gener_status_e48158_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedautomotivenews',
            index=models.Index(fields=['published_at'], name='intel_gener_publish_a9102a_idx'),
        ),
    ]
