# Generated by Django 5.2.9 on 2026-07-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel', '0008_automotive_news_foundation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automotivebrief',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('ready', 'Готово к генерации'), ('used', 'Использовано'), ('rejected', 'Отклонено')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='evidence_level',
            field=models.IntegerField(choices=[(0, 'Анонимный или неподтверждённый источник'), (1, 'Публикация средства массовой информации'), (2, 'Есть первичный или официальный источник'), (3, 'Подтверждено источниками разных типов')], default=1),
        ),
        migrations.AlterField(
            model_name='generatedautomotivenews',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('review', 'На проверке'), ('approved', 'Одобрено'), ('published', 'Опубликовано'), ('rejected', 'Отклонено'), ('error', 'Ошибка')], db_index=True, default='review', max_length=20),
        ),
        migrations.AlterField(
            model_name='generatedmedicalnews',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('review', 'На проверке'), ('approved', 'Одобрено'), ('published', 'Опубликовано'), ('rejected', 'Отклонено'), ('error', 'Ошибка')], db_index=True, default='review', max_length=20),
        ),
        migrations.AlterField(
            model_name='medicalbrief',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('ready', 'Готово к генерации'), ('used', 'Использовано'), ('rejected', 'Отклонено')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='regionaldigest',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('ready', 'Готово к генерации'), ('review', 'На проверке'), ('published', 'Опубликовано'), ('rejected', 'Отклонено'), ('error', 'Ошибка')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='source',
            name='cadence',
            field=models.CharField(choices=[('hot', 'Часто — каждые 5–15 минут'), ('medium', 'Обычно — каждые 1–3 часа'), ('cold', 'Редко — каждые 6–24 часа')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='source',
            name='region',
            field=models.CharField(choices=[('EU', 'Европа'), ('WORLD', 'Мир'), ('RU', 'Россия')], max_length=10),
        ),
        migrations.AlterField(
            model_name='source',
            name='source_class',
            field=models.CharField(choices=[('agency', 'Информационное агентство'), ('official', 'Официальный источник'), ('stats', 'Статистический источник'), ('industry', 'Отраслевой источник'), ('commentary', 'Экспертные комментарии')], max_length=20),
        ),
        migrations.AlterField(
            model_name='source',
            name='topic',
            field=models.CharField(choices=[('economy', 'Экономика'), ('politics', 'Политика'), ('it', 'Информационные технологии'), ('auto', 'Автомобили'), ('medicine', 'Медицина'), ('labs', 'Лабораторная диагностика')], max_length=20),
        ),
    ]
