# Generated by Django 5.2.9 on 2026-07-15 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel', '0009_russian_admin_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalbrief',
            name='semantic_anchor',
            field=models.CharField(blank=True, help_text='Анкор внутренней ссылки на карточку анализа.', max_length=500, verbose_name='Анкор внутренней ссылки'),
        ),
        migrations.AddField(
            model_name='medicalbrief',
            name='semantic_assigned_at',
            field=models.DateTimeField(blank=True, help_text='Дата последнего назначения посадочной страницы.', null=True, verbose_name='Дата назначения посадочной страницы'),
        ),
        migrations.AddField(
            model_name='medicalbrief',
            name='semantic_feed_sha256',
            field=models.CharField(blank=True, help_text='SHA256 semantic feed, по которому выполнен подбор.', max_length=64, verbose_name='SHA256 семантического каталога'),
        ),
        migrations.AddField(
            model_name='medicalbrief',
            name='semantic_match_details',
            field=models.JSONField(blank=True, default=dict, help_text='Детали детерминированного сопоставления.', verbose_name='Детали семантического совпадения'),
        ),
        migrations.AddField(
            model_name='medicalbrief',
            name='semantic_panel_code',
            field=models.CharField(blank=True, help_text='Код анализа в каталоге КДЛ «Дзагуров».', max_length=64, verbose_name='Код анализа КДЛ «Дзагуров»'),
        ),
        migrations.AddField(
            model_name='medicalbrief',
            name='semantic_panel_id',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, help_text='ID панели в каталоге КДЛ «Дзагуров».', null=True, verbose_name='ID панели КДЛ «Дзагуров»'),
        ),
        migrations.AddField(
            model_name='medicalbrief',
            name='semantic_panel_title',
            field=models.TextField(blank=True, help_text='Название выбранной карточки анализа.', verbose_name='Название карточки анализа'),
        ),
        migrations.AddField(
            model_name='medicalbrief',
            name='semantic_panel_url',
            field=models.URLField(blank=True, help_text='Абсолютный URL выбранной карточки анализа.', max_length=500, verbose_name='URL карточки анализа'),
        ),
        migrations.AddField(
            model_name='medicalbrief',
            name='semantic_score',
            field=models.IntegerField(default=0, help_text='Итоговая оценка релевантности выбранной карточки.', verbose_name='Оценка семантического совпадения'),
        ),
    ]
