from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [("intel", "0010_medical_brief_semantic_fields")]

    operations = [
        migrations.CreateModel(
            name="ContentProject",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.SlugField(max_length=80, unique=True, verbose_name="Ключ проекта")),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                ("niche", models.CharField(max_length=200, verbose_name="Тематика")),
                ("audience", models.CharField(max_length=300, verbose_name="Целевая аудитория")),
                ("locale", models.CharField(default="ru-RU", max_length=20, verbose_name="Локаль")),
                ("brand_name", models.CharField(blank=True, max_length=200, verbose_name="Бренд")),
                ("site_url", models.URLField(blank=True, max_length=500, verbose_name="Сайт")),
                ("system_prompt", models.TextField(blank=True, verbose_name="Системные инструкции")),
                ("policy", models.JSONField(blank=True, default=dict, help_text="Настройки риска, источников, экспертной проверки и запрещённых утверждений.", verbose_name="Политика качества")),
                ("is_enabled", models.BooleanField(default=True, verbose_name="Проект включён")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создано")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлено")),
            ],
            options={"verbose_name": "Контентный проект", "verbose_name_plural": "Контентные проекты", "ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="ContentTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.SlugField(max_length=80, verbose_name="Ключ шаблона")),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                ("content_type", models.CharField(default="evergreen_article", max_length=50, verbose_name="Тип материала")),
                ("instructions", models.TextField(verbose_name="Инструкции")),
                ("min_chars", models.PositiveIntegerField(default=1800, verbose_name="Минимум символов")),
                ("max_chars", models.PositiveIntegerField(default=4000, verbose_name="Максимум символов")),
                ("min_sections", models.PositiveSmallIntegerField(default=3, verbose_name="Минимум разделов")),
                ("expert_review_required", models.BooleanField(default=True, verbose_name="Требуется экспертная проверка")),
                ("is_enabled", models.BooleanField(default=True, verbose_name="Шаблон включён")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создано")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлено")),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="templates", to="intel.contentproject", verbose_name="Проект")),
            ],
            options={"verbose_name": "Шаблон контента", "verbose_name_plural": "Шаблоны контента", "ordering": ["project", "name"]},
        ),
        migrations.CreateModel(
            name="ContentBrief",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("cluster_key", models.SlugField(max_length=160, verbose_name="Ключ кластера")),
                ("title", models.CharField(max_length=300, verbose_name="Рабочий заголовок")),
                ("primary_keyword", models.CharField(max_length=300, verbose_name="Главный запрос")),
                ("secondary_keywords", models.JSONField(blank=True, default=list, verbose_name="Дополнительные запросы")),
                ("search_intent", models.CharField(default="informational", max_length=80, verbose_name="Поисковое намерение")),
                ("evidence_pack", models.JSONField(default=list, help_text="Список объектов: id, claim, source_url, source_title.", verbose_name="Пакет доказательств")),
                ("internal_links", models.JSONField(blank=True, default=list, help_text="Список объектов: url, anchor.", verbose_name="Внутренние ссылки")),
                ("instructions", models.TextField(blank=True, verbose_name="Дополнительные инструкции")),
                ("status", models.CharField(choices=[("draft", "Черновик"), ("ready", "Готово к генерации"), ("used", "Использовано"), ("rejected", "Отклонено")], db_index=True, default="draft", max_length=20, verbose_name="Статус")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создано")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлено")),
                ("used_at", models.DateTimeField(blank=True, null=True, verbose_name="Использовано")),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="briefs", to="intel.contentproject", verbose_name="Проект")),
                ("template", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="briefs", to="intel.contenttemplate", verbose_name="Шаблон")),
            ],
            options={"verbose_name": "Универсальное редакционное задание", "verbose_name_plural": "Универсальные редакционные задания", "ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="GeneratedContent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=300, verbose_name="Заголовок")),
                ("slug", models.SlugField(db_index=True, max_length=255, verbose_name="URL")),
                ("meta_description", models.CharField(max_length=320, verbose_name="Мета-описание")),
                ("body", models.TextField(verbose_name="Текст Markdown")),
                ("used_evidence_ids", models.JSONField(default=list, verbose_name="Использованные доказательства")),
                ("source_urls", models.JSONField(default=list, verbose_name="Источники")),
                ("qa_report", models.JSONField(default=dict, verbose_name="Отчёт проверки")),
                ("quality_score", models.PositiveSmallIntegerField(default=0, verbose_name="Оценка качества")),
                ("status", models.CharField(choices=[("review", "На проверке"), ("approved", "Одобрено"), ("published", "Опубликовано"), ("rejected", "Отклонено"), ("error", "Ошибка")], db_index=True, default="review", max_length=20, verbose_name="Статус")),
                ("reviewer_name", models.CharField(blank=True, max_length=200, verbose_name="Проверил")),
                ("reviewed_at", models.DateTimeField(blank=True, null=True, verbose_name="Проверено")),
                ("llm_model", models.CharField(blank=True, max_length=120, verbose_name="LLM")),
                ("llm_prompt", models.TextField(blank=True, verbose_name="Запрос LLM")),
                ("llm_response_raw", models.TextField(blank=True, verbose_name="Ответ LLM")),
                ("llm_elapsed_ms", models.PositiveIntegerField(blank=True, null=True, verbose_name="Время генерации, мс")),
                ("llm_error", models.TextField(blank=True, verbose_name="Ошибка")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создано")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлено")),
                ("published_at", models.DateTimeField(blank=True, null=True, verbose_name="Опубликовано")),
                ("brief", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="generated_items", to="intel.contentbrief", verbose_name="Задание")),
            ],
            options={"verbose_name": "Универсальный материал", "verbose_name_plural": "Универсальные материалы", "ordering": ["-created_at"]},
        ),
        migrations.AddConstraint(model_name="contenttemplate", constraint=models.UniqueConstraint(fields=("project", "key"), name="intel_unique_content_template")),
        migrations.AddConstraint(model_name="contentbrief", constraint=models.UniqueConstraint(fields=("project", "cluster_key"), name="intel_unique_content_cluster")),
        migrations.AddIndex(model_name="contentbrief", index=models.Index(fields=["project", "status", "-created_at"], name="intel_conte_project_99040e_idx")),
        migrations.AddIndex(model_name="generatedcontent", index=models.Index(fields=["status", "-created_at"], name="intel_gener_status_aa4d09_idx")),
        migrations.AddIndex(model_name="generatedcontent", index=models.Index(fields=["brief", "status"], name="intel_gener_brief_i_6b7f84_idx")),
    ]
